SEGMENT_LEN = 100
TRAIN_HEADER_COUNT = 5000
TEST_HEADER_COUNT = 10000

TRAIN_SEGMENT_COUNT = TRAIN_HEADER_COUNT // SEGMENT_LEN
TEST_SEGMENT_COUNT = TEST_HEADER_COUNT // SEGMENT_LEN

DEV_USERS_COUNT = 10